<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Dota2MetaChecker.Common</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Interfaces\"/>
    </ItemGroup>

</Project>
